version: '3'

services:
  influxdb:
    image: influxdb
    hostname: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb

  emqx:
    image: emqx/emqx
    hostname: emqx
    environment: 
      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_mnesia"
      EMQX_AUTH__MNESIA__AS: ${EMQX_AUTH_AS}
      EMQX_AUTH__MNESIA__PASSWORD_HASH: "sha256"
      EMQX_AUTH__MNESIA__1__LOGIN: ${EMQX_ADMIN_USERNAME}
      EMQX_AUTH__MNESIA__1__PASSWORD: ${EMQX_ADMIN_PASSWORD}
      EMQX_AUTH__MNESIA__1__IS_SUPERUSER: "true"
      EMQX_AUTH__MNESIA__2__LOGIN: ${TELEGRAF_EMQX_CLIENT_ID}
      EMQX_AUTH__MNESIA__2__PASSWORD: ${TELEGRAF_EMQX_PASSWORD}
      EMQX_AUTH__MNESIA__2__IS_SUPERUSER: "false"
    ports:
      - "18083:18083"
      - "1883:1883"
      - "8081:8081"

  telegraf:
    image: telegraf
    hostname: telegraf
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
    depends_on: 
      - influxdb
      - emqx
    links: 
      - influxdb
      - emqx
    environment:
      INFLUXDB_URL: ${INFLUXDB_URL}
      DATABASE_NAME: ${INFLUXDB_DATABASE_NAME}
      EMQX_URL: ${EMQX_URL}
      EMQX_CLIENT_ID: ${TELEGRAF_EMQX_CLIENT_ID}
      EMQX_CLIENT_USERNAME: ${TELEGRAF_EMQX_CLIENT_ID}
      EMQX_CLIENT_PASSWORD: ${TELEGRAF_EMQX_PASSWORD}
    volumes: 
      - ${PWD}/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  chronograf:
    image: chronograf
    hostname: chronograf
    ports: 
      - "8888:8888"
    links: 
      - influxdb
    volumes: 
      - chronograf-data:/var/lib/chronograf

  grafana:
    image: grafana/grafana
    ports: 
      - "3000:3000"
    links: 
      - influxdb
    environment: 
      GF_INSTALL_PLUGINS: "grafana-piechart-panel,grafana-clock-panel,grafana-worldmap-panel,briangann-datatable-panel"
    volumes: 
      - grafana-data:/var/lib/grafana
      - ${PWD}/grafana-plugins:/var/lib/grafana/plugins


volumes:
  influxdb-data:
  chronograf-data:
  grafana-data: